import Foundation

enum AccessibilityID {
    static let tabBlock = "tab-block"
    static let tabSchedule = "tab-schedule"
    static let tabActivity = "tab-activity"
    static let tabSettings = "tab-settings"
    static let blockButton = "block-button"
    static let manageModes = "manage-modes"
    static let modesBack = "modes-back"
    static let settingsKeys = "settings-keys"
    static let settingsRules = "settings-rules"
    static let settingsEmergency = "settings-emergency"
    static let settingsHelp = "settings-help"
    static let settingsContact = "settings-contact"
    static let settingsAbout = "settings-about"
    static let settingsNotifications = "settings-notifications"
    static let notificationsToggle = "notifications-toggle"
    static let navBack = "nav-back"
    static let activityScroll = "activity-scroll"
    static let scheduleRoot = "schedule-root"
    static let addKey = "add-key"
    static let tapNFC = "tap-nfc"
    static let scanQR = "scan-qr"
    static let modeEdit = "mode-edit"
    static let emergencyUse = "emergency-use"
    static let emergencyConfirm = "emergency-confirm"
    static let emergencyCount = "emergency-count"
    static let onboardingContinue = "onboarding-continue"
    static let onboardingNote = "onboarding-note"
    static let homeAddKey = "home-add-key"
}
